In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [ ]:
tf._version_

In [4]:
dataset=pd.read_csv('Churn_Modelling.csv')

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
# We are going to predict which customer leave and which does not 

In [6]:
x=dataset.iloc[:,3:-1].values

In [9]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
y=dataset.iloc[:,-1].values

In [11]:
# For gender and Geography

from sklearn.preprocessing import LabelEncoder

In [28]:
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [14]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
# Since  geography has more than 1 hence we will use ONEHOTENCODER

In [19]:
 from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder

In [34]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))


In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=365)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


In [37]:
# Building ANN

ann=tf.keras.models.Sequential()

In [38]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [39]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [40]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [43]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [44]:
ann.fit(X_train,Y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 913us/step - loss: 0.6869 - accuracy: 0.6557
Epoch 2/100
250/250 [==============================] - 0s 936us/step - loss: 0.5162 - accuracy: 0.7999
Epoch 3/100
250/250 [==============================] - 0s 848us/step - loss: 0.4629 - accuracy: 0.8070
Epoch 4/100
250/250 [==============================] - 0s 783us/step - loss: 0.4453 - accuracy: 0.8084
Epoch 5/100
250/250 [==============================] - 0s 789us/step - loss: 0.4371 - accuracy: 0.8111
Epoch 6/100
250/250 [==============================] - 0s 713us/step - loss: 0.4289 - accuracy: 0.8125
Epoch 7/100
250/250 [==============================] - 0s 721us/step - loss: 0.4208 - accuracy: 0.8129
Epoch 8/100
250/250 [==============================] - 0s 729us/step - loss: 0.4118 - accuracy: 0.8169
Epoch 9/100
250/250 [==============================] - 0s 778us/step - loss: 0.4009 - accuracy: 0.8257
Epoch 10/100
250/250 [==============================] - 0s 731us/step - l

250/250 [==============================] - 0s 764us/step - loss: 0.3342 - accuracy: 0.8649
Epoch 80/100
250/250 [==============================] - 0s 785us/step - loss: 0.3340 - accuracy: 0.8648
Epoch 81/100
250/250 [==============================] - 0s 955us/step - loss: 0.3335 - accuracy: 0.8639
Epoch 82/100
250/250 [==============================] - 0s 874us/step - loss: 0.3339 - accuracy: 0.8637
Epoch 83/100
250/250 [==============================] - 0s 923us/step - loss: 0.3337 - accuracy: 0.8636
Epoch 84/100
250/250 [==============================] - 0s 722us/step - loss: 0.3336 - accuracy: 0.8645
Epoch 85/100
250/250 [==============================] - 0s 743us/step - loss: 0.3338 - accuracy: 0.8654
Epoch 86/100
250/250 [==============================] - 0s 758us/step - loss: 0.3336 - accuracy: 0.8654
Epoch 87/100
250/250 [==============================] - 0s 770us/step - loss: 0.3336 - accuracy: 0.8624
Epoch 88/100
250/250 [==============================] - 0s 758us/step - loss:

In [55]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,3,1,1,50000]]))>0.5)

[[ True]]


In [64]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
#print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [59]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [60]:
cm=confusion_matrix(Y_test,y_pred)
print(cm)

[[1526   61]
 [ 214  199]]


In [61]:
accuracy_score(Y_test,y_pred)

0.8625